version: '3'

services:
  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src/wordpress:/app
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - script

  script:
    build: .  # Utilise le Dockerfile pour construire l'image PHP
    container_name: script
    volumes:
      - ./src/wordpress:/app

  data:
    image: mysql:latest
    container_name: data
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
